### ISSUE TITLE
How to create and update CHANGELOG.md with Github Action.

### ISSUE THREAD

**Issue by cable8mm** [cable8mm/github#1]

**Comment by cable8mm** [comment]
1. create action yml.
2. create CHANGELOG.md with "# Release Notes" heading.

No need to change setting.

```yml
name: update changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  update:
    permissions:
      contents: write
    uses: cable8mm/.github/.github/workflows/update-changelog.yml@main
```

Good job!
